---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1-1
    hooks:
      - id: no-commit-to-branch
        args: [--branch=develop]
        language_version: python3.6
      - id: debug-statements
        language_version: python3.6
      - id: end-of-file-fixer
        language_version: python3.6
#  - repo: https://github.com/asottile/seed-isort-config
#    rev: v1.1.0
#    hooks:
#      - id: seed-isort-config
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.4
#    hooks:
#      - id: isort
#        language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.0.0.dev2  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        directory: [garden, tasks, fabfile]
        language_version: python3.6
